
export enum UserActions {
    USER_ACTION_START_FETCHING = 'USER_ACTION_START_FETCHING',
    USER_ACTION_DATA_RETRIEVED = 'USER_ACTION_DATA_RETRIEVED',
    USER_ACTION_DATA_ERROR = 'USER_ACTION_DATA_ERROR',
};

